# Generated by Django 6.0.1 on 2026-02-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('jobs', '0004_alter_joboffer_apply_link_alter_joboffer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='jobs.joboffer'),
        ),
    ]
