# Generated by Django 6.0.1 on 2026-02-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboffer_apply_link_joboffer_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='All', max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('jobs_found', models.IntegerField(default=0)),
                ('jobs_added', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido'), ('WARNING', 'Advertencia')], default='SUCCESS', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={},
        ),
    ]
