# Generated by Django 6.0.1 on 2026-02-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_scrapinglog_alter_joboffer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='apply_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
