# Generated by Django 6.0.1 on 2026-03-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_joboffer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si está activo, la oferta será visible para los usuarios. Si no, quedará oculta.', verbose_name='¿Oferta visible?'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Salario máximo numérico. Útil para búsquedas y filtros. Puedes dejarlo vacío si solo usas 'Salary range'.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Salario mínimo numérico. Útil para búsquedas y filtros. Puedes dejarlo vacío si solo usas 'Salary range'.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_range',
            field=models.CharField(blank=True, help_text="Texto libre para mostrar el rango salarial, por ejemplo: 'USD 2000-3000/mes' o 'A convenir'.", max_length=100),
        ),
    ]
