# Generated by Django 6.0.2 on 2026-02-12 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Resumen profesional', max_length=500)),
                ('title', models.CharField(blank=True, help_text='e.g., Inspector API 510, Técnico NDT Nivel II', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Base de operaciones', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('willing_to_travel', models.BooleanField(default=False, verbose_name='Disponible para viajar')),
                ('offshore_experience', models.BooleanField(default=False, verbose_name='Experiencia Offshore')),
                ('has_driving_license', models.BooleanField(default=False, verbose_name='Licencia de Conducir')),
                ('linkedin_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
