# Generated by Django 6.0.1 on 2026-02-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profilepost_profilepostcomment_profilepostreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepost',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profilepost',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
