# Generated by Django 6.0.1 on 2026-02-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profilepost_link_profilepost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilepost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
