# Generated by Django 6.0.1 on 2026-03-09 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_serviciofreelance_serviciofreelancevaloracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciofreelance',
            name='precio',
            field=models.CharField(help_text='Precio, rango o a convenir', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviciofreelancevaloracion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
